CREATE TABLE aluno (id INT AUTO_INCREMENT NOT NULL, pessoa_id INT DEFAULT NULL, matricula VARCHAR(10) NOT NULL, cgu VARCHAR(10) NOT NULL, INDEX fk_aluno_pessoa1_idx (pessoa_id), UNIQUE INDEX matricula_UNIQUE (matricula), UNIQUE INDEX cgu_UNIQUE (cgu), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE campus (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(25) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE etapa (id INT AUTO_INCREMENT NOT NULL, etapa_tipo_id INT DEFAULT NULL, semestre_id INT DEFAULT NULL, nome VARCHAR(25) NOT NULL, data_inicio DATETIME NOT NULL, data_fim DATETIME NOT NULL, peso INT NOT NULL, ordem INT NOT NULL, enviar_email_administrador TINYINT(1) NOT NULL, enviar_email_banca TINYINT(1) NOT NULL, enviar_email_orientador TINYINT(1) NOT NULL, INDEX fk_etapa_semestre1_idx (semestre_id), INDEX fk_etapa_etapa_tipo1_idx (etapa_tipo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE etapa_entrega (id INT AUTO_INCREMENT NOT NULL, aluno_id INT DEFAULT NULL, etapa_id INT DEFAULT NULL, etapa_status_id INT DEFAULT NULL, data DATETIME NOT NULL, INDEX fk_etapa_entrega_etapa1_idx (etapa_id), INDEX fk_etapa_entrega_aluno1_idx (aluno_id), INDEX fk_etapa_entrega_etapa_status1_idx (etapa_status_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE etapa_entrega_arquivo (id INT AUTO_INCREMENT NOT NULL, etapa_entrega_id INT DEFAULT NULL, nome VARCHAR(255) NOT NULL, tipo VARCHAR(25) NOT NULL, caminho VARCHAR(255) NOT NULL, INDEX fk_etapa_entrega_arquivo_etapa_entrega1_idx (etapa_entrega_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE etapa_nota (id INT AUTO_INCREMENT NOT NULL, etapa_entrega_id INT DEFAULT NULL, professor_id INT DEFAULT NULL, nota VARCHAR(25) NOT NULL, INDEX fk_etapa_nota_professor1_idx (professor_id), INDEX fk_etapa_nota_etapa_entrega1_idx (etapa_entrega_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE etapa_status (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(25) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE etapa_tipo (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(25) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE pessoa (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, telefone VARCHAR(25) NOT NULL, sexo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE professor (id INT AUTO_INCREMENT NOT NULL, pessoa_id INT DEFAULT NULL, assinatura VARCHAR(255) DEFAULT NULL, INDEX fk_professor_pessoa1_idx (pessoa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE semestre (id INT AUTO_INCREMENT NOT NULL, campus_id INT DEFAULT NULL, nome VARCHAR(25) NOT NULL, data_inicio DATE NOT NULL, data_fim DATE NOT NULL, tipo INT DEFAULT NULL, INDEX fk_semestre_campus1_idx (campus_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE tcc (id INT AUTO_INCREMENT NOT NULL, aluno_id INT DEFAULT NULL, semestre_id INT DEFAULT NULL, titulo VARCHAR(255) NOT NULL, INDEX fk_aluno_tcc_aluno1_idx (aluno_id), INDEX fk_tcc_semestre1_idx (semestre_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE tcc_professor (id INT AUTO_INCREMENT NOT NULL, professor_id INT DEFAULT NULL, tcc_id INT DEFAULT NULL, tipo TINYINT(1) NOT NULL, INDEX fk_tcc_banca_tcc1_idx (tcc_id), INDEX fk_tcc_banca_professor1_idx (professor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE usuario (id INT AUTO_INCREMENT NOT NULL, pessoa_id INT DEFAULT NULL, usuario_acesso_id INT DEFAULT NULL, senha VARCHAR(25) NOT NULL, INDEX fk_usuario_usuario_acesso_idx (usuario_acesso_id), INDEX fk_usuario_pessoa1_idx (pessoa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE usuario_acesso (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(25) NOT NULL, nivel INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE aluno ADD CONSTRAINT FK_67C97100DF6FA0A5 FOREIGN KEY (pessoa_id) REFERENCES pessoa (id);
ALTER TABLE etapa ADD CONSTRAINT FK_2F32B1C4AFA29CBB FOREIGN KEY (etapa_tipo_id) REFERENCES etapa_tipo (id);
ALTER TABLE etapa ADD CONSTRAINT FK_2F32B1C45577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id);
ALTER TABLE etapa_entrega ADD CONSTRAINT FK_E3E8ABBCB2DDF7F4 FOREIGN KEY (aluno_id) REFERENCES aluno (id);
ALTER TABLE etapa_entrega ADD CONSTRAINT FK_E3E8ABBCC5EE35FA FOREIGN KEY (etapa_id) REFERENCES etapa (id);
ALTER TABLE etapa_entrega ADD CONSTRAINT FK_E3E8ABBCF63DC6D0 FOREIGN KEY (etapa_status_id) REFERENCES etapa_status (id);
ALTER TABLE etapa_entrega_arquivo ADD CONSTRAINT FK_A8A47EC34927CDCF FOREIGN KEY (etapa_entrega_id) REFERENCES etapa_entrega (id);
ALTER TABLE etapa_nota ADD CONSTRAINT FK_195D20614927CDCF FOREIGN KEY (etapa_entrega_id) REFERENCES etapa_entrega (id);
ALTER TABLE etapa_nota ADD CONSTRAINT FK_195D20617D2D84D5 FOREIGN KEY (professor_id) REFERENCES professor (id);
ALTER TABLE professor ADD CONSTRAINT FK_790DD7E3DF6FA0A5 FOREIGN KEY (pessoa_id) REFERENCES pessoa (id);
ALTER TABLE semestre ADD CONSTRAINT FK_71688FBCAF5D55E1 FOREIGN KEY (campus_id) REFERENCES campus (id);
ALTER TABLE tcc ADD CONSTRAINT FK_36D21118B2DDF7F4 FOREIGN KEY (aluno_id) REFERENCES aluno (id);
ALTER TABLE tcc ADD CONSTRAINT FK_36D211185577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id);
ALTER TABLE tcc_professor ADD CONSTRAINT FK_34D800D97D2D84D5 FOREIGN KEY (professor_id) REFERENCES professor (id);
ALTER TABLE tcc_professor ADD CONSTRAINT FK_34D800D94F70A726 FOREIGN KEY (tcc_id) REFERENCES tcc (id);
ALTER TABLE usuario ADD CONSTRAINT FK_2265B05DDF6FA0A5 FOREIGN KEY (pessoa_id) REFERENCES pessoa (id);
ALTER TABLE usuario ADD CONSTRAINT FK_2265B05D6A41B146 FOREIGN KEY (usuario_acesso_id) REFERENCES usuario_acesso (id);
