-- MySQL Script generated by MySQL Workbench
-- Mon Sep 26 00:39:05 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistema_tcc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sistema_tcc` ;

-- -----------------------------------------------------
-- Schema sistema_tcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_tcc` DEFAULT CHARACTER SET utf8 ;
USE `sistema_tcc` ;

-- -----------------------------------------------------
-- Table `sistema_tcc`.`usuario_acesso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_tcc`.`usuario_acesso` ;

CREATE TABLE IF NOT EXISTS `sistema_tcc`.`usuario_acesso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  `nivel` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_tcc`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_tcc`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `sistema_tcc`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(25) NOT NULL,
  `sexo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_tcc`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_tcc`.`usuario` ;

CREATE TABLE IF NOT EXISTS `sistema_tcc`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `senha` VARCHAR(25) NOT NULL,
  `usuario_acesso_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_usuario_acesso_idx` (`usuario_acesso_id` ASC),
  INDEX `fk_usuario_pessoa1_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_usuario_usuario_acesso`
    FOREIGN KEY (`usuario_acesso_id`)
    REFERENCES `sistema_tcc`.`usuario_acesso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `sistema_tcc`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_tcc`.`campus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_tcc`.`campus` ;

CREATE TABLE IF NOT EXISTS `sistema_tcc`.`campus` (
  `id` INT NOT NULL,
  `nome` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_tcc`.`semestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_tcc`.`semestre` ;

CREATE TABLE IF NOT EXISTS `sistema_tcc`.`semestre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `tipo` INT NULL,
  `campus_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_semestre_campus1_idx` (`campus_id` ASC),
  CONSTRAINT `fk_semestre_campus1`
    FOREIGN KEY (`campus_id`)
    REFERENCES `sistema_tcc`.`campus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Configuração do semestre.';


-- -----------------------------------------------------
-- Table `sistema_tcc`.`etapa_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_tcc`.`etapa_tipo` ;

CREATE TABLE IF NOT EXISTS `sistema_tcc`.`etapa_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Tipos de etapas.';


-- -----------------------------------------------------
-- Table `sistema_tcc`.`etapa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_tcc`.`etapa` ;

CREATE TABLE IF NOT EXISTS `sistema_tcc`.`etapa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `peso` INT NOT NULL,
  `ordem` INT NOT NULL,
  `enviar_email_administrador` TINYINT(1) NOT NULL,
  `enviar_email_banca` TINYINT(1) NOT NULL,
  `enviar_email_orientador` TINYINT(1) NOT NULL,
  `semestre_id` INT NOT NULL,
  `etapa_tipo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_etapa_semestre1_idx` (`semestre_id` ASC),
  INDEX `fk_etapa_etapa_tipo1_idx` (`etapa_tipo_id` ASC),
  CONSTRAINT `fk_etapa_semestre1`
    FOREIGN KEY (`semestre_id`)
    REFERENCES `sistema_tcc`.`semestre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etapa_etapa_tipo1`
    FOREIGN KEY (`etapa_tipo_id`)
    REFERENCES `sistema_tcc`.`etapa_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Configuração das etapas.';


-- -----------------------------------------------------
-- Table `sistema_tcc`.`professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_tcc`.`professor` ;

CREATE TABLE IF NOT EXISTS `sistema_tcc`.`professor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assinatura` VARCHAR(255) NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_professor_pessoa1_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_professor_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `sistema_tcc`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_tcc`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_tcc`.`aluno` ;

CREATE TABLE IF NOT EXISTS `sistema_tcc`.`aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(10) NOT NULL,
  `cgu` VARCHAR(10) NOT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC),
  UNIQUE INDEX `cgu_UNIQUE` (`cgu` ASC),
  INDEX `fk_aluno_pessoa1_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_aluno_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `sistema_tcc`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_tcc`.`etapa_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_tcc`.`etapa_status` ;

CREATE TABLE IF NOT EXISTS `sistema_tcc`.`etapa_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_tcc`.`etapa_entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_tcc`.`etapa_entrega` ;

CREATE TABLE IF NOT EXISTS `sistema_tcc`.`etapa_entrega` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `aluno_id` INT NOT NULL,
  `etapa_id` INT NOT NULL,
  `etapa_status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_etapa_entrega_etapa1_idx` (`etapa_id` ASC),
  INDEX `fk_etapa_entrega_aluno1_idx` (`aluno_id` ASC),
  INDEX `fk_etapa_entrega_etapa_status1_idx` (`etapa_status_id` ASC),
  CONSTRAINT `fk_etapa_entrega_etapa1`
    FOREIGN KEY (`etapa_id`)
    REFERENCES `sistema_tcc`.`etapa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etapa_entrega_aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `sistema_tcc`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etapa_entrega_etapa_status1`
    FOREIGN KEY (`etapa_status_id`)
    REFERENCES `sistema_tcc`.`etapa_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Entregas referente a uma etapa, feita pelos aluno.';


-- -----------------------------------------------------
-- Table `sistema_tcc`.`etapa_nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_tcc`.`etapa_nota` ;

CREATE TABLE IF NOT EXISTS `sistema_tcc`.`etapa_nota` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `professor_id` INT NOT NULL,
  `etapa_entrega_id` INT NOT NULL,
  `nota` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_etapa_nota_professor1_idx` (`professor_id` ASC),
  INDEX `fk_etapa_nota_etapa_entrega1_idx` (`etapa_entrega_id` ASC),
  CONSTRAINT `fk_etapa_nota_professor1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `sistema_tcc`.`professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etapa_nota_etapa_entrega1`
    FOREIGN KEY (`etapa_entrega_id`)
    REFERENCES `sistema_tcc`.`etapa_entrega` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Nota de uma entrega.';


-- -----------------------------------------------------
-- Table `sistema_tcc`.`tcc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_tcc`.`tcc` ;

CREATE TABLE IF NOT EXISTS `sistema_tcc`.`tcc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `aluno_id` INT NOT NULL,
  `semestre_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aluno_tcc_aluno1_idx` (`aluno_id` ASC),
  INDEX `fk_tcc_semestre1_idx` (`semestre_id` ASC),
  CONSTRAINT `fk_aluno_tcc_aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `sistema_tcc`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tcc_semestre1`
    FOREIGN KEY (`semestre_id`)
    REFERENCES `sistema_tcc`.`semestre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Dados do TCC.';


-- -----------------------------------------------------
-- Table `sistema_tcc`.`tcc_professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_tcc`.`tcc_professor` ;

CREATE TABLE IF NOT EXISTS `sistema_tcc`.`tcc_professor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tcc_id` INT NOT NULL,
  `professor_id` INT NOT NULL,
  `tipo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tcc_banca_tcc1_idx` (`tcc_id` ASC),
  INDEX `fk_tcc_banca_professor1_idx` (`professor_id` ASC),
  CONSTRAINT `fk_tcc_banca_tcc1`
    FOREIGN KEY (`tcc_id`)
    REFERENCES `sistema_tcc`.`tcc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tcc_banca_professor1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `sistema_tcc`.`professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Relaciona os professores banca com o TCC.';


-- -----------------------------------------------------
-- Table `sistema_tcc`.`etapa_entrega_arquivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_tcc`.`etapa_entrega_arquivo` ;

CREATE TABLE IF NOT EXISTS `sistema_tcc`.`etapa_entrega_arquivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(25) NOT NULL,
  `caminho` VARCHAR(255) NOT NULL,
  `etapa_entrega_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_etapa_entrega_arquivo_etapa_entrega1_idx` (`etapa_entrega_id` ASC),
  CONSTRAINT `fk_etapa_entrega_arquivo_etapa_entrega1`
    FOREIGN KEY (`etapa_entrega_id`)
    REFERENCES `sistema_tcc`.`etapa_entrega` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
